global:
  max_text_length: 30
  character_dict_path: 'dict/korean_english_digits_symbols.txt'

dataset:
  ext_op_transfrom_idx: 1 
  transforms_train:
    - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape: [32, 100, 3]
          max_text_length: 30
    - RecAug:
    - Albumentation:
    - CTCLabelEncode:
    - SVTRRecResizeImg:
        image_shape: [3, 64, 256]
        padding: true
  transforms_test:
    - CTCLabelEncode:
    - SVTRRecResizeImg:
        image_shape: [3, 64, 256]
        padding: true